//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCodeDev.Blazor.Foundation.Doc.Core.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenCodeDev.Blazor.Foundation.Doc.Core.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accordion.
        /// </summary>
        public static string Accordion_Menu {
            get {
                return ResourceManager.GetString("Accordion_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accordion Menu.
        /// </summary>
        public static string Accordion_Menu_Menu {
            get {
                return ResourceManager.GetString("Accordion_Menu_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppWrapper.
        /// </summary>
        public static string AppWrapper_Setup_Menu {
            get {
                return ResourceManager.GetString("AppWrapper_Setup_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge.
        /// </summary>
        public static string Badge_Menu {
            get {
                return ResourceManager.GetString("Badge_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Styles.
        /// </summary>
        public static string Base_Styles_Menu {
            get {
                return ResourceManager.GetString("Base_Styles_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breadcrumbs.
        /// </summary>
        public static string Breadcrumbs_Menu {
            get {
                return ResourceManager.GetString("Breadcrumbs_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Group.
        /// </summary>
        public static string Button_Group_Menu {
            get {
                return ResourceManager.GetString("Button_Group_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        public static string Button_Menu {
            get {
                return ResourceManager.GetString("Button_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callout.
        /// </summary>
        public static string Callout_Menu {
            get {
                return ResourceManager.GetString("Callout_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        public static string Card_Menu {
            get {
                return ResourceManager.GetString("Card_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carousel (Orbit).
        /// </summary>
        public static string Carousel_Orbit_Menu {
            get {
                return ResourceManager.GetString("Carousel_Orbit_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string Clipboard_Menu {
            get {
                return ResourceManager.GetString("Clipboard_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Highlighter.
        /// </summary>
        public static string Code_Highlighter_Menu {
            get {
                return ResourceManager.GetString("Code_Highlighter_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility.
        /// </summary>
        public static string Compatibility_Menu {
            get {
                return ResourceManager.GetString("Compatibility_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Containers.
        /// </summary>
        public static string Containers_Menu_Header {
            get {
                return ResourceManager.GetString("Containers_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        public static string Controls_Menu_Header {
            get {
                return ResourceManager.GetString("Controls_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging Tool.
        /// </summary>
        public static string Debugging_Tool_Menu_Header {
            get {
                return ResourceManager.GetString("Debugging_Tool_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drilldown Menu.
        /// </summary>
        public static string Drilldown_Menu_Menu {
            get {
                return ResourceManager.GetString("Drilldown_Menu_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdown.
        /// </summary>
        public static string Dropdown_Menu {
            get {
                return ResourceManager.GetString("Dropdown_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdown Menu.
        /// </summary>
        public static string Dropdown_Menu_Menu {
            get {
                return ResourceManager.GetString("Dropdown_Menu_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexbox.
        /// </summary>
        public static string Flexbox_Menu {
            get {
                return ResourceManager.GetString("Flexbox_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float Classes.
        /// </summary>
        public static string Float_Classes_Menu {
            get {
                return ResourceManager.GetString("Float_Classes_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        public static string Forms_Menu {
            get {
                return ResourceManager.GetString("Forms_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General_Menu_Header {
            get {
                return ResourceManager.GetString("General_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        public static string Getting_Started_Menu_Header {
            get {
                return ResourceManager.GetString("Getting_Started_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Styles.
        /// </summary>
        public static string Global_Styles_Menu {
            get {
                return ResourceManager.GetString("Global_Styles_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helper Classes.
        /// </summary>
        public static string Helper_Classes_Menu {
            get {
                return ResourceManager.GetString("Helper_Classes_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons.
        /// </summary>
        public static string Icons_Menu {
            get {
                return ResourceManager.GetString("Icons_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        public static string Installation_Menu {
            get {
                return ResourceManager.GetString("Installation_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string Label_Menu {
            get {
                return ResourceManager.GetString("Label_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded Modules.
        /// </summary>
        public static string Load_Module_Menu {
            get {
                return ResourceManager.GetString("Load_Module_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below is the list of all loaded module for this documentation app..
        /// </summary>
        public static string Load_Module_Subtitle {
            get {
                return ResourceManager.GetString("Load_Module_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded Modules.
        /// </summary>
        public static string Load_Module_Title {
            get {
                return ResourceManager.GetString("Load_Module_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization.
        /// </summary>
        public static string Localization_Menu {
            get {
                return ResourceManager.GetString("Localization_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalStorage.
        /// </summary>
        public static string LocalStorage_Menu {
            get {
                return ResourceManager.GetString("LocalStorage_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Design Icons.
        /// </summary>
        public static string Material_Design_Icons_Menu {
            get {
                return ResourceManager.GetString("Material_Design_Icons_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string Media_Menu_Header {
            get {
                return ResourceManager.GetString("Media_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Object.
        /// </summary>
        public static string Media_Object_Menu {
            get {
                return ResourceManager.GetString("Media_Object_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu_Menu {
            get {
                return ResourceManager.GetString("Menu_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        public static string Module_Assembly {
            get {
                return ResourceManager.GetString("Module_Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Module_Version {
            get {
                return ResourceManager.GetString("Module_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion UI.
        /// </summary>
        public static string Motion_UI_Menu {
            get {
                return ResourceManager.GetString("Motion_UI_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string Navigation_Menu_Header {
            get {
                return ResourceManager.GetString("Navigation_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off-Canvas.
        /// </summary>
        public static string Off_Canvas_Menu {
            get {
                return ResourceManager.GetString("Off_Canvas_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagination.
        /// </summary>
        public static string Pagination_Menu {
            get {
                return ResourceManager.GetString("Pagination_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string Plugins_Menu_Header {
            get {
                return ResourceManager.GetString("Plugins_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progess Bar.
        /// </summary>
        public static string Progess_Bar_Menu {
            get {
                return ResourceManager.GetString("Progess_Bar_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prototyping.
        /// </summary>
        public static string Prototyping_Menu {
            get {
                return ResourceManager.GetString("Prototyping_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsive Accordion Tabs.
        /// </summary>
        public static string Responsive_Accordion_Tabs_Menu {
            get {
                return ResourceManager.GetString("Responsive_Accordion_Tabs_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsive Embed.
        /// </summary>
        public static string Responsive_Embed_Menu {
            get {
                return ResourceManager.GetString("Responsive_Embed_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reveal.
        /// </summary>
        public static string Reveal_Menu {
            get {
                return ResourceManager.GetString("Reveal_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup_Menu_Header {
            get {
                return ResourceManager.GetString("Setup_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        public static string Slider_Menu {
            get {
                return ResourceManager.GetString("Slider_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticky.
        /// </summary>
        public static string Sticky_Menu {
            get {
                return ResourceManager.GetString("Sticky_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style Management.
        /// </summary>
        public static string Style_Management_Menu {
            get {
                return ResourceManager.GetString("Style_Management_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        public static string Switch_Menu {
            get {
                return ResourceManager.GetString("Switch_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Table_Menu {
            get {
                return ResourceManager.GetString("Table_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabs.
        /// </summary>
        public static string Tabs_Menu {
            get {
                return ResourceManager.GetString("Tabs_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail.
        /// </summary>
        public static string Thumbnail_Menu {
            get {
                return ResourceManager.GetString("Thumbnail_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip.
        /// </summary>
        public static string Tooltip_Menu {
            get {
                return ResourceManager.GetString("Tooltip_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Bar.
        /// </summary>
        public static string Top_Bar_Menu {
            get {
                return ResourceManager.GetString("Top_Bar_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typography.
        /// </summary>
        public static string Typography_Menu_Header {
            get {
                return ResourceManager.GetString("Typography_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        public static string Utilities_Menu_Header {
            get {
                return ResourceManager.GetString("Utilities_Menu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility Classes.
        /// </summary>
        public static string Visibility_Classes_Menu {
            get {
                return ResourceManager.GetString("Visibility_Classes_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome_Menu {
            get {
                return ResourceManager.GetString("Welcome_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XY Grid.
        /// </summary>
        public static string XY_Grid_Menu {
            get {
                return ResourceManager.GetString("XY_Grid_Menu", resourceCulture);
            }
        }
    }
}
